name: test_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  http:
  flutter: 
    sdk: flutter
  dartz: ^0.9.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.5

flutter: 
  uses-material-design: true

